#pragma once

enum PRIMITIVE_TYPES
{
    PRIMITIVE_TRIANGLE,
    PRIMITIVE_QUAD,
    PRIMITIVE_CIRCLE,
    PRIMITIVE_POINT,
    PRIMITIVE_LINE,
    PRIMITIVE_LINES,
};

enum PRIMITIVE_ALGO
{
    LINE_NAIVE_ALGORITHM,
    LINE_DEFAULT_ALGORITHM,
    //LINE_BRESENHAM_ALGORITHM,
    //LINE_WU_ALGORITHM,
    CIRCLE_SIMPLE_ALGORITHM,
    CIRCLE_SYM4_ALGORITHM,
    CIRCLE_SYM8_ALGORITHM,
};