#pragma once

enum PRIMITIVE_TYPES
{
    PRIMITIVE_TRIANGLE,
    PRIMITIVE_QUAD,
    PRIMITIVE_CIRCLE,
    PRIMITIVE_POINT,
    PRIMITIVE_LINE,
    PRIMITIVE_LINES,
    PRIMITIVE_ELLIPSE,
};

enum PRIMITIVE_ALGO
{
    LINE_NAIVE_ALGORITHM,
    LINE_DEFAULT_ALGORITHM,
    CIRCLE_DEFAULT_ALGORITHM,
    CIRCLE_SYM4_ALGORITHM,
    CIRCLE_SYM8_ALGORITHM,
    ELLIPSE_DEFAULT_ALGORITHM,
    ELLIPSE_SYM4_ALGORITHM,
};