#pragma once

enum TERRAIN_TYPES
{
    GRASS_TILE,
    BANK_TILE_1,
    BANK_TILE_2,
    BANK_TILE_3,
    BANK_TILE_4,
    BANK_TILE_5,
    BANK_TILE_6,
    BANK_TILE_7,
    BANK_TILE_8,
    BANK_TILE_9,
    BANK_TILE_10,
    BANK_TILE_11,
    BANK_TILE_12,
    WATER_TILE,
};